name: .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Notissimus.sln

    - name: Build
      run: dotnet build Notissimus.sln --no-restore

    - name: Test
      run: dotnet test Notissimus.sln --no-build --verbosity normal